// Edit modal: blank-field feedback, and focus after a failed PUT/DELETE (server forced to 500).
const { chromium } = require('@playwright/test');
const path = require('path');
const U = require(path.resolve(__dirname, '../../../../users.json')).find((u) => u.username === 'buggy');
const T = `[a11y] edit-errors ${Date.now()}`;
const act = (p) => p.evaluate(() => { const e = document.activeElement; return e === document.body ? 'BODY (focus lost)' : `${e.tagName} ${e.id || e.innerText.trim().slice(0, 20)}`; });
(async () => {
  const b = await chromium.launch({ headless: true });
  const p = await b.newPage();
  await p.goto('http://localhost:5173/login');
  await p.fill('#username', U.username); await p.fill('#password', U.password); await p.click('button[type=submit]');
  await p.waitForSelector('tbody tr button');
  const id = await p.evaluate(async (t) => (await (await fetch('/api/bugs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: t, severity: 'low', owner: 'buggy', description: 'a11y' }) })).json()).id, T);
  await p.reload(); await p.waitForSelector('tbody tr button');
  await p.getByRole('textbox', { name: 'Search bugs by title' }).fill(T);
  await p.locator('tbody tr button', { hasText: T }).focus(); await p.keyboard.press('Enter');
  await p.waitForSelector('#edit-bug-title');
  await p.locator('#edit-bug-title').fill('');
  const r = await p.evaluate(() => ({ saveDisabled: document.querySelector('[role=dialog] button[type=submit]').disabled, titleInvalid: document.getElementById('edit-bug-title').getAttribute('aria-invalid'), alerts: [...document.querySelectorAll('[role=dialog] [role=alert]')].map((a) => a.textContent) }));
  console.log('Edit, title cleared:', JSON.stringify(r));
  await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); await p.keyboard.press('Tab');
  console.log('Tab stops after Description reach:', await act(p), '(Save is skipped while disabled)');
  await p.locator('#edit-bug-title').fill(T + ' x');
  await p.route(`**/api/bugs/${id}`, (rt) => (['PUT', 'DELETE'].includes(rt.request().method()) ? rt.fulfill({ status: 500, contentType: 'application/json', body: '{"message":"Injected failure"}' }) : rt.continue()));
  await p.locator('[role=dialog] button[type=submit]').focus(); await p.keyboard.press('Enter');
  await p.waitForSelector('[role=dialog] [role=alert]'); await p.waitForTimeout(300);
  console.log('After failed PUT via Enter on Save:', await act(p));
  await p.locator('#edit-bug-title').focus(); await p.keyboard.press('Enter');
  await p.waitForTimeout(500);
  console.log('After failed PUT via Enter in Title:', await act(p));
  await p.getByRole('dialog', { name: /Edit bug/ }).getByRole('button', { name: 'Delete' }).focus(); await p.keyboard.press('Enter');
  await p.waitForSelector('[aria-labelledby=confirm-delete-title]');
  await p.keyboard.press('Tab'); await p.keyboard.press('Enter');
  await p.waitForTimeout(600);
  console.log('After failed DELETE via confirm:', await act(p), '| confirm open:', await p.locator('[aria-labelledby=confirm-delete-title]').count());
  await p.unroute(`**/api/bugs/${id}`);
  await p.request.delete(`http://localhost:5173/api/bugs/${id}`);
  console.log('cleanup: deleted own bug', id);
  await b.close();
})();
